include(FindPackageHandleStandardArgs)

if (NOT WIN32 AND NOT APPLE)
  find_package(PkgConfig)
  if (PKG_CONFIG_FOUND)
    pkg_check_modules(SAMPLERATE samplerate)
  endif ()
endif ()

if ( NOT SAMPLERATE_FOUND )
  find_path(SAMPLERATE_INCLUDE_DIRS NAMES samplerate.h)
  find_library(SAMPLERATE_LIBRARIES NAMES samplerate)

  if ( NOT "${SAMPLERATE_LIBRARIES}" STREQUAL "")
    set (SAMPLERATE_FOUND TRUE)
    set (SAMPLERATE_LINK_LIBRARIES ${SAMPLERATE_LINK_LIBRARIES} ${SAMPLERATE_LIBRARIES})
  endif ()
endif ()

if ( SAMPLERATE_INCLUDEDIR AND NOT SAMPLERATE_INCLUDE_DIRS )
  set (SAMPLERATE_INCLUDE_DIRS ${SAMPLERATE_INCLUDEDIR})
endif ()
  
find_package_handle_standard_args(SampleRate DEFAULT_MSG SAMPLERATE_LIBRARIES SAMPLERATE_INCLUDE_DIRS)

if ( SAMPLERATE_FOUND AND NOT TARGET SampleRate::samplerate )
  add_library(SampleRate::samplerate INTERFACE IMPORTED GLOBAL)
  set_target_properties(SampleRate::samplerate
    PROPERTIES
      VERSION "${SAMPLERATE_VERSION}"
      LOCATION "${SAMPLERATE_LINK_LIBRARIES}"
      INTERFACE_INCLUDE_DIRECTORIES "${SAMPLERATE_INCLUDE_DIRS}"
      INTERFACE_LINK_LIBRARIES "${SAMPLERATE_LINK_LIBRARIES}")
endif ()
